version: "3.9"

services:
  malware_inference:
    image: mohamedahsan00/malware-detector:latest
    # add build: . to build from current dir
    build: .
    container_name: malware_inference
    volumes:
      - ./network_logs:/input/logs
      - ./output:/output
    restart: always


